POST http://localhost:9080/register HTTP/1.1
Content-Type: application/json

{
    "username": "radha",
    "password": "123456",
    "email": "radha@email.com",
    "name": "HarHari"
}

###

Post http://localhost:9080/login HTTP/1.1
Content-Type:  application/json

{
    "email": "radha@email.com",
    "password": "123456"
}


###

GET http://localhost:9080/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token": "dc55234c488dabbc44651f20dae9dfe904ecdb879909dc1e4516d200ab65808f"
}


###


POST http://localhost:9080/update_profile_data HTTP/1.1
Content-Type: application/json

{
    "token": "8a211dac6b1555abbe4f06cd34eb10c2903cd985e4f23c78781a5ad15fbd348e",
    "bio": "Experienced software engineer",
    "currentPost": "SDE",
    "postWork": [
        {
            "company": "Goldman Sachs SDE-1",
            "position": "Software Engineer FullStack",
            "years": "2.5+"
        }
    ],
    "education": [
        {
            "school": "IIT Bombay",
            "degree": "B.Tech",
            "fieldOfStudy": "2023-2027"
        }
    ]
}



### 

GET http://localhost:9080/user/get_all_users HTTP/1.1