POST http://localhost:9080/register HTTP/1.1
Content-Type: application/json

{
    "username": "Sujal",
    "password": "123456",
    "email": "Sujal@email.com",
    "name": "Sujal"
}

###

Post http://localhost:9090/login HTTP/1.1
Content-Type:  application/json

{
    "email": "Sujal@email.com",
    "password": "123456"
}


###

GET http://localhost:9090/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token": "ee08a646e446cfa07aa6124e7bae36013b32f1a160ab616177e973e930c1123a"
}


###


POST http://localhost:9080/update_profile_data HTTP/1.1
Content-Type: application/json

{
    "token": "5e81dbe7b2920d6974c6583502c8d76a854f5e0451a5aaaef7c5b0aa29039001",
    "bio": "Software engineer",
    "currentPost": "SDE-2",
    "postWork": [
        {
            "company": "Google",
            "position": "Software Engineer",
            "years": "2.5+"
        }
    ],
    "education": [
        {
            "school": "IIT Mumbai",
            "degree": "B.Tech",
            "fieldOfStudy": "2023-2026"
        }
    ]
}



### 

GET http://localhost:9080/user/get_all_users HTTP/1.1